name: Release

on: [push]

env:
  SOLUTION_NAME: ScreenRecorderLib
  PROJECT_NAME: ScreenRecorderLib

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - run: nuget restore ${{ env.SOLUTION_NAME }}.sln
    - run: msbuild /m '/p:Configuration=Release;Platform="${{ matrix.platform }}"' ${{ env.SOLUTION_NAME }}.sln
    - name: Archive Release {{ matrix.platform }}
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: ${{ env.PROJECT_NAME }}\bin\${{ matrix.platform }}\Release\ScreenRecorderLib.dll
        filename: 'Release.{{ matrix.platform }}.zip'
        exclusions: '*.pdg *.metagen *.xml'
  release:
      name: Upload Release
      runs-on: windows-latest
      needs : build
      steps:
        - uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: |
              LICENSE.txt
                *.zip
