name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  SOLUTION_NAME: ScreenRecorderLib
  PROJECT_NAME: ScreenRecorderLib

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: windows-2019
    strategy:
      matrix:
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - run: nuget restore ${{ env.SOLUTION_NAME }}.sln
    - run: msbuild /m '/p:Configuration=Release;Platform="${{ matrix.platform }}"' ${{ env.SOLUTION_NAME }}.sln
    - name: Archive Release ${{ matrix.platform }}
    - uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: ${{ env.PROJECT_NAME }}\bin\${{ matrix.platform }}\Release\ScreenRecorderLib.dll
        filename: ScreenRecorderLib.${{matrix.platform}}.zip
        exclusions: '*.pdg *.metagen *.xml'
        
    - uses: actions/upload-artifact@v3
      with:
        name: ScreenRecorderLib.${{matrix.platform}}.zip
        path: ScreenRecorderLib.${{matrix.platform}}.zip
        
  release:
      name: Upload Release
      runs-on: windows-2019
      needs : build
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: ScreenRecorderLib.x86.zip
            path: ScreenRecorderLib.x86.zip
        - uses: actions/download-artifact@v3
          with:
            name: ScreenRecorderLib.x64.zip
            path: ScreenRecorderLib.x64.zip
        - name: Display structure of downloaded files
          run: ls -R
        - uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: |
              LICENSE
              *.zip
